# -*- coding: utf-8 -*-
"""petting_zoo_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMjAj_2NG8tkqPNTna6gDghFjtglzJ6u
"""

# エミュレータとGymnasiumのインストール
!pip install gymnasium[atari]
!pip install gymnasium[accept-rom-license]
!pip install pyvirtualdisplay > /dev/null 2>&1
!pip install AutoROM[accept-rom-license]
!AutoROM --accept-license
# 描画用のシステムパッケージ
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1
!pip install pettingzoo[atari,accept-rom-license]
!pip install "pettingzoo[sisl]"
!pip install supersuit

!pip uninstall -y box2d-py

import imageio
from pettingzoo.sisl import pursuit_v4

# GIFの保存先ファイル名
video_filename = "pursuit_random_agents.gif"

# 環境生成（render_mode="rgb_array" で画像取得可能にする）
env = pursuit_v4.env(render_mode="rgb_array")

# フレームを格納するリスト
frames = []

# 環境リセット
env.reset()

max_frames = 400  # 保存したい最大フレーム数
frame_count = 0

# ランダムエージェントで実行し、各ステップの画面を保存
for agent in env.agent_iter():
    obs, reward, terminated, truncated, info = env.last()

    # 画面を画像として取得
    frame = env.render()
    frames.append(frame)
    frame_count += 1

    # 指定フレーム数に達したらループを抜ける
    if frame_count >= max_frames:
        break

    if terminated or truncated:
        action = None
    else:
        action = env.action_space(agent).sample()

    env.step(action)

env.close()

# フレームをGIFにエンコードして保存
from scipy.ndimage import zoom
from PIL import Image
import numpy as np

def resize_frame(frame, scale=0.5):
    h, w, c = frame.shape
    resized = zoom(frame, (scale, scale, 1), order=1)
    return resized.astype(frame.dtype)

def quantize_frame(frame, colors=64):
    img = Image.fromarray(frame)
    img_quantized = img.quantize(colors=colors)
    return np.array(img_quantized.convert("RGB"))

# 軽量化したGIFを保存
with imageio.get_writer("pursuit_small.gif", fps=5) as video:
    for frame in frames:
        small = resize_frame(frame, scale=0.5)
        q_small = quantize_frame(small, colors=16)
        video.append_data(q_small)

print(f"GIFを保存しました: {video_filename}")

import numpy as np
from pettingzoo.sisl import pursuit_v4

class PursuitWrapper:
    def __init__(self, render_mode=None, max_cycles=500, obs_range=7):
        # チームとしての共通目的を維持するため shared_reward=True で環境を初期化
        self.env = pursuit_v4.env(
            render_mode=render_mode,
            max_cycles=max_cycles,
            shared_reward=True
        )
        self.obs_range = obs_range
        self.center_idx = obs_range // 2  # 7x7 の中心 (3, 3) が自分自身の位置

        self.possible_agents = self.env.possible_agents
        self.num_agents = len(self.possible_agents)

        self.obs_dim = (obs_range * obs_range * 3)
        self.state_dim = self.obs_dim * self.num_agents

        self.action_space = self.env.action_space(self.possible_agents[0])
        self.action_dim = self.action_space.n

        # ハイブリッド報酬の重みパラメータ
        self.distance_reward_scale = 0.15     # 獲物へ接近したときの報酬
        self.coop_reward_scale = 0.2         # 獲物の近くで味方と連携したときの報酬
        self.flanking_bonus_scale = 0.2      # 他に味方がいないルートから回り込んだときの報酬
        self.surround_reward = 2.0           # 3人以上で包囲網を形成したときの報酬

        # 衝突ペナルティ（進路妨害や壁への衝突による無駄な動きを抑制）
        self.collision_penalty = -0.1

        # エージェントごとの前ステップの「最も近い獲物への距離」を記録する辞書
        self.prev_min_distances = {}

    def reset(self):
        self.env.reset()
        self.prev_min_distances = {agent: None for agent in self.possible_agents}

    def get_obs(self, agent):
        if agent not in self.env.agents:
            return None
        obs, _, _, _, _ = self.env.last(agent)
        if obs is None:
            return None
        return obs

    def get_global_state(self):
        """
        全員の観測を純粋にリスト化して結合し、(num_agents, obs_dim) の構造の元データを作成する
        """
        obs_list = []
        for agent in self.possible_agents:
            obs = self.get_obs(agent)
            if obs is not None:
                # 7x7x3 画像を 147次元のフラットなベクトルに変換
                obs_list.append(obs.reshape(-1).astype(np.float32))
            else:
                obs_list.append(np.zeros(self.obs_dim, dtype=np.float32))

        # 全員分を結合 (num_agents * obs_dim,) の1次元として返す
        # （※MultiAgentBufferに保存され、サンプリング時に再び (Batch, num_agents, obs_dim) に復元されます）
        return np.concatenate(obs_list)

    def _analyze_observation(self, obs):
        """
        1つのエージェントの観測(7, 7, 3)から報酬計算用の情報を抽出する
        """
        if obs is None:
            return None, 0, 0

        prey_layer = obs[:, :, 2]
        ally_layer = obs[:, :, 1]

        prey_positions = np.argwhere(prey_layer > 0)

        min_dist = float('inf')
        closest_prey_pos = None
        cy, cx = self.center_idx, self.center_idx

        # 1. 最も近い獲物を特定
        for py, px in prey_positions:
            dist = abs(py - cy) + abs(px - cx)
            if dist < min_dist:
                min_dist = dist
                closest_prey_pos = (py, px)

        if min_dist == float('inf'):
            return None, 0, 0  # 視界内に獲物がいない場合

        # 2. 協調判定：自分の隣接4マスにいる味方の総数
        allies_count = 0
        neighbors = [(cy-1, cx), (cy+1, cx), (cy, cx-1), (cy, cx+1)]
        for ny, nx in neighbors:
            if 0 <= ny < self.obs_range and 0 <= nx < self.obs_range:
                allies_count += ally_layer[ny, nx]

        # 3. 獲物がいる「方向（セクター）」に他の味方が何人いるかをカウント
        py, px = closest_prey_pos
        flank_allies = 0

        if py < cy:
            flank_allies += np.sum(ally_layer[0:cy, :])
        elif py > cy:
            flank_allies += np.sum(ally_layer[cy+1:, :])

        if px < cx:
            flank_allies += np.sum(ally_layer[:, 0:cx])
        elif px > cx:
            flank_allies += np.sum(ally_layer[:, cx+1:])

        return min_dist, allies_count, flank_allies

    def step(self, agent, action):
        if agent not in self.env.agents:
            return 0.0, True, True, {}

        current_cycle = getattr(self.env.unwrapped, 'cycles', 0)

        _, _, terminated, truncated, _ = self.env.last(agent)
        step_action = None if (terminated or truncated) else action

        self.env.step(step_action)

        if agent not in self.env.agents:
            return 0.0, True, True, {}

        obs, team_reward, terminated, truncated, info = self.env.last(agent)

        # -----------------------------------------------------------------
        # 🌟 個別評価報酬（Individual Reward）の計算開始
        # -----------------------------------------------------------------
        individual_reward = 0.0

        # 観測データから距離、周囲の味方数を抽出
        current_min_dist, allies_count, flank_allies = self._analyze_observation(obs)

        # 1. 距離・回り込みベースの評価
        reward_distance = 0.0
        prev_dist = self.prev_min_distances.get(agent)

        if current_min_dist is not None and prev_dist is not None:
            change = prev_dist - current_min_dist
            reward_distance = change * self.distance_reward_scale
            # 獲物に向かって進んでおり、かつそのルートにまだ味方がいない（孤立して回り込んでいる）場合ボーナス
            if change > 0 and flank_allies == 0:
                reward_distance += self.flanking_bonus_scale

        self.prev_min_distances[agent] = current_min_dist
        individual_reward += reward_distance

        # 2. 協調行動（接近＋包囲網）の評価
        reward_coop = 0.0
        if current_min_dist is not None and current_min_dist <= 2:
            if allies_count >= 1:
                reward_coop += self.coop_reward_scale
            if allies_count >= 3:
                reward_coop += self.surround_reward
        individual_reward += reward_coop

        # 3. 衝突ペナルティの評価（無駄な移動の抑制）
        # Pursuit環境では移動が失敗した際（衝突等）に info['wasted_move'] が True になります
        if info.get('wasted_move', False):
            individual_reward += self.collision_penalty

        # 4. チーム全員の完全捕獲成功時の個別時間ボーナス
        if terminated and not truncated:
            if team_reward > 0:
                time_bonus = max(0, 500 - current_cycle) * 1.0
                individual_reward += (500.0 + time_bonus)
                print(f"--- 🎉 TRUE CAPTURE SUCCESS! Agent: {agent} | Bonus: {500.0 + time_bonus} ---")

        # -----------------------------------------------------------------
        # 🌟 ハイブリッド報酬の合算（チーム共通報酬 ＋ 各自の個別評価）
        # -----------------------------------------------------------------
        hybrid_reward = team_reward + individual_reward

        return hybrid_reward, terminated, truncated, info

    def render(self):
        """
        環境の現在の画面をキャプチャして返します。
        推論用スクリプトで frames.append() して gif に保存するために使用します。
        """
        # 1. 内部環境（pettingzooのenv）の現在の render_mode を取得
        render_mode = getattr(self.env, "render_mode", None)

        if render_mode is None:
            return None

        # 2. mode が "human" もしくは "rgb_array" の場合、env.render() を呼び出す
        # pursuit_v4 の仕様上、render() は直接画像（numpy array）を返すか、
        # もしくは内部のスクリーンバッファから画像を取得する必要があります。
        frame = self.env.render()

        # 3. もし render_mode="human" で、かつ render() が None を返す（画面描画のみ行う）場合、
        # pygame のサーフェスから直接ピクセル配列をキャプチャします。
        if frame is None and render_mode == "human":
            try:
                import pygame
                # 現在表示されている pygame 画面を文字列（RGB）として取得し、numpy 配列に変換
                screen = pygame.display.get_surface()
                if screen is not None:
                    # ピクセルデータを RGB 形式のバイト文字列で取得
                    img_str = pygame.image.tostring(screen, "RGB")
                    # numpy 配列 [横, 縦, 3] に変換してから、一般的な画像形式 [縦, 横, 3] に変形
                    frame = np.frombuffer(img_str, dtype=np.uint8).reshape(screen.get_size()[1], screen.get_size()[0], 3)
            except Exception as e:
                # pygame が入っていない、もしくはインポートエラーなどの保険
                pass

        return frame

env = PursuitWrapper(render_mode="rgb_array", max_cycles=500)

# リセット
env.reset()

# MAPPO側で agent_iter を回す
for agent in env.env.agent_iter():
    # 観測を取得（存在確認あり）
    obs = env.get_obs(agent)
    global_state = env.get_global_state()

    # dead かどうかを確認（存在確認あり）
    if agent not in env.env.agents:
        action = None
    else:
        _, _, terminated, truncated, _ = env.env.last(agent)
        is_dead = terminated or truncated
        if is_dead:
            action = None
        else:
            # ここでMAPPOのポリシーに基づき行動を選択
            action = env.action_space.sample()  # 例: ランダム

    # 1ステップ進める（ラッパ内で存在確認あり）
    reward, terminated, truncated, info = env.step(agent, action)

    # バッファに保存など...
    # (obs, action, reward, terminated, truncated, ...)

env.close()

import torch
import torch.nn as nn
from torch.distributions import Categorical
import torch.optim as optim

import torch
import torch.nn as nn
from torch.distributions import Categorical

class CNNEncoder(nn.Module):
    def __init__(self, obs_shape=(7,7,3), channels=(16, 32)):
        super().__init__()
        c_in = obs_shape[-1]
        c1, c2 = channels

        self.cnn = nn.Sequential(
            nn.Conv2d(c_in, c1, kernel_size=3, stride=1, padding=1),
            nn.GELU(),  # 🌟 ReLU から GELU に変更
            nn.Conv2d(c1, c2, kernel_size=3, stride=1, padding=1),
            nn.GELU(),  # 🌟 ReLU から GELU に変更
            nn.Flatten()
        )
        # CNN出力の次元（7*7*32 = 1568）
        self.output_dim = 7 * 7 * c2

    def forward(self, obs):
        """
        Args:
            obs: (batch_size, 147) のフラット観測テンソル
        Returns:
            features: (batch_size, cnn_output_dim) の特徴ベクトル
        """
        # (batch_size, 147) -> (batch_size, 7, 7, 3)
        obs = obs.view(-1, 7, 7, 3)
        # (batch_size, 7, 7, 3) -> (batch_size, 3, 7, 7)
        obs = obs.permute(0, 3, 1, 2)
        features = self.cnn(obs)
        return features


# MAPPO Actor: ID情報を付与し、パラメータを共有して使用
class MAPPO_Actor(nn.Module):
    def __init__(self, cnn_encoder, num_agents=8, id_dim=8, act_dim=5, hidden_size=256):
        super().__init__()
        self.cnn = cnn_encoder

        # エージェントIDの埋め込み層
        self.id_embedding = nn.Embedding(num_embeddings=num_agents, embedding_dim=id_dim)

        # 入力サイズ = CNN特徴量(1568) + ID埋め込み(8)
        input_dim = self.cnn.output_dim + id_dim

        self.mlp = nn.Sequential(
            nn.Linear(input_dim, hidden_size),
            nn.GELU(),  # 🌟 ReLU から GELU に変更
            nn.Linear(hidden_size, hidden_size),
            nn.GELU(),  # 🌟 ReLU から GELU に変更
            nn.Linear(hidden_size, act_dim)
        )

    def forward(self, obs, agent_id):
        """
        Args:
            obs: (batch_size, 147) 単一エージェントの観測
            agent_id: (batch_size,) 単一エージェントのID
        """
        # 空間特徴量の抽出
        features = self.cnn(obs)

        # ID特徴量の抽出
        if agent_id.dim() == 2:
            agent_id = agent_id.squeeze(-1)
        id_feats = self.id_embedding(agent_id)

        # 特徴量の結合
        x = torch.cat([features, id_feats], dim=-1)

        # 行動分布の出力
        logits = self.mlp(x)
        dist = Categorical(logits=logits)
        return dist


class MAPPO_Critic(nn.Module):
    def __init__(self, cnn_encoder, num_agents, agent_emb_dim=16):
        super(MAPPO_Critic, self).__init__()
        self.num_agents = num_agents
        self.cnn_encoder = cnn_encoder

        # 🌟 【重要修正】cnn_encoder が配置されているデバイス（CPU or GPU）を自動取得
        device = next(cnn_encoder.parameters()).device

        # ダミーデータを使って、CNNEncoder の本当の出力サイズを自動計測する
        with torch.no_grad():
            # 🛠️ ダミーテンソルを cnn_encoder と同じデバイス（GPU）に送る
            dummy_obs = torch.zeros(1, 147, device=device)
            dummy_features = self.cnn_encoder(dummy_obs)
            # 実際の出力次元を取得
            self.cnn_feature_dim = dummy_features.shape[-1]

        print(f"[MAPPO_Critic] 自動検出されたCNN出力次元: {self.cnn_feature_dim}")

        # ターゲットエージェントのID埋め込み
        self.agent_embedding = nn.Embedding(num_agents, agent_emb_dim)

        # 全員の特徴量（自動計測値 * num_agents） + 対象エージェントID（agent_emb_dim）
        input_dim = (self.cnn_feature_dim * num_agents) + agent_emb_dim

        # 特徴ベクトルの集まりを処理するMLP
        self.v_head = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.GELU(),
            nn.Linear(128, 128),
            nn.GELU(),
            nn.Linear(128, 64),
            nn.GELU(),
            nn.Linear(64, 1)
        )

    def forward(self, global_states, target_agent_id):
        # デバイスの統一（引数がCPUのままの場合に備える）
        device = next(self.parameters()).device
        global_states = global_states.to(device)
        target_agent_id = target_agent_id.to(device)

        # 形状の安全な復元
        if global_states.dim() == 1:
            # 1176次次元を (8, 147) に復元
            global_states = global_states.view(self.num_agents, -1)
        if global_states.dim() == 2:
            global_states = global_states.unsqueeze(0) # (1, 8, 147)

        batch_size = global_states.size(0)

        # 1. 各エージェントの観測を個別にCNNに通す
        flat_obs = global_states.view(batch_size * self.num_agents, -1)
        agent_features = self.cnn_encoder(flat_obs) # (batch*num_agents, 1568)

        # 2. 全員分の特徴量を1つのバッチベクトルに再結合
        # 自動計測したサイズを使うため、12544個の要素が綺麗に (batch_size, 12544) に収まります
        combined_features = agent_features.view(batch_size, self.num_agents * self.cnn_feature_dim)

        # 3. 評価対象エージェントのID情報を結合
        if target_agent_id.dim() == 0:
            target_agent_id = target_agent_id.unsqueeze(0)

        agent_emb = self.agent_embedding(target_agent_id)
        x = torch.cat([combined_features, agent_emb], dim=-1)

        # 4. 価値 V(s) の算出
        value = self.v_head(x)
        return value


# =====================================================================
# 2. MAPPO トレーナークラス
# =====================================================================
class MAPPO:
    def __init__(self, num_agents, obs_dim, state_dim, action_dim,
                 lr_actor=3e-5, lr_critic=3e-5, gamma=0.99, gae_lambda=0.95,
                 clip_epsilon=0.2, value_coef=0.5, entropy_coef=0.01,
                 device=torch.device("cpu")):
        self.num_agents = num_agents
        self.obs_dim = obs_dim
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.gamma = gamma
        self.gae_lambda = gae_lambda
        self.clip_epsilon = clip_epsilon
        self.value_coef = value_coef
        self.entropy_coef = entropy_coef
        self.device = device

        # CNNエンコーダ（Actor/Criticで独立して管理）
        self.cnn_encoder = CNNEncoder().to(device)
        self.critic_encoder = CNNEncoder().to(device) # 画像処理用Criticエンコーダ

        # ID情報に対応したActorとCritic
        self.actor = MAPPO_Actor(self.cnn_encoder, num_agents=num_agents, act_dim=action_dim).to(device)
        self.critic = MAPPO_Critic(self.critic_encoder, num_agents=num_agents).to(device)

        # 最適化器
        self.optimizer_actor = optim.Adam(self.actor.parameters(), lr=lr_actor)
        self.optimizer_critic = optim.Adam(self.critic.parameters(), lr=lr_critic)

        self.buffer = MultiAgentBuffer(num_agents, obs_dim, state_dim, action_dim)

    def get_action(self, obs, greedy=False):
        """
        観測から行動とlog_probを取得
        Args:
            obs: (num_agents, obs_dim) のテンソル
        """
        obs = obs.to(self.device)

        # 固有IDテンソルの作成 [0, 1, 2, ..., num_agents-1]
        agent_ids = torch.arange(self.num_agents, dtype=torch.long, device=self.device)

        with torch.no_grad():
            # ID情報を付与してポリシーに送る
            dist = self.actor(obs, agent_ids)

            if greedy:
                actions = torch.argmax(dist.logits, dim=-1)
            else:
                actions = dist.sample()

            log_probs = dist.log_prob(actions)

            return actions.cpu().numpy(), log_probs.cpu().numpy()

    def get_value_for_agent(self, state, agent_id):
        """
        🌟 追加: 特定のエージェント視点での中央集中型Criticの価値を算出する
        学習ループ内での個々の努力評価（ハイブリッド報酬の計算・蓄積）に使用します。

        Args:
            state: (1, num_agents, obs_dim) または (num_agents * obs_dim,) のテンソル
            agent_id: torch.tensor([i], dtype=torch.long)
        """
        # 形状の安全な復元
        if state.dim() == 1:
            state = state.view(self.num_agents, self.obs_dim)
        if state.dim() == 2:
            state = state.unsqueeze(0) # (1, num_agents, obs_dim)

        state = state.to(self.device)
        agent_id = agent_id.to(self.device)

        with torch.no_grad():
            value = self.critic(state, agent_id)
            return value.item()

    def get_value(self, state):
        """
        互換性のために維持: 従来のグローバル状態から代表（エージェント0）の価値を返す
        Args:
            state: (num_agents * obs_dim,) または (num_agents, obs_dim) のテンソル
        """
        dummy_agent_id = torch.tensor([0], dtype=torch.long, device=self.device)
        return self.get_value_for_agent(state, dummy_agent_id)

    def update(self, batch, epochs=3):
        if batch is None:
            return 0.0, 0.0, 0.0

        batch_size = batch['obs'].shape[0]

        obs = torch.FloatTensor(batch['obs']).to(self.device)                  # (batch, num_agents, obs_dim)
        actions = torch.LongTensor(batch['actions']).to(self.device)           # (batch, num_agents)
        old_log_probs = torch.FloatTensor(batch['log_probs']).to(self.device)   # (batch, num_agents)
        advantages = torch.FloatTensor(batch['advantages']).to(self.device)     # (batch, num_agents)
        returns = torch.FloatTensor(batch['rewards']).to(self.device)           # (batch, num_agents) ※実質は個別リターン

        # グローバル状態（全員の観測の並び）
        global_states = torch.FloatTensor(batch['global_states']).to(self.device)

        # 🛠️ 変更点: Criticに (batch_size, num_agents, obs_dim) の形状で綺麗に渡すため、
        # もしバッファから2次元で出てきても確実に3次元(B, N, D)に整形する
        if global_states.dim() == 2:
            global_states = global_states.view(batch_size, self.num_agents, self.obs_dim)

        # Advantageの正規化（バッチ次元のみ）
        advantages = (advantages - advantages.mean(dim=0, keepdim=True)) / (advantages.std(dim=0, keepdim=True) + 1e-8)

        actor_losses = []
        critic_losses = []
        entropies = []

        # 更新で使い回すバッチサイズ分の基本IDシーケンス
        batch_agent_ids = torch.arange(self.num_agents, dtype=torch.long, device=self.device).repeat(batch_size, 1)

        for epoch in range(epochs):
            # --- 1. Actorの更新 ---
            flat_obs = obs.view(-1, self.obs_dim)
            flat_ids = batch_agent_ids.view(-1)

            # IDを付与してフォワードパス
            dist = self.actor(flat_obs, flat_ids)

            new_log_probs = dist.log_prob(actions.view(-1)).view(batch_size, self.num_agents)
            entropy = dist.entropy().view(batch_size, self.num_agents).mean()

            ratio = torch.exp(new_log_probs - old_log_probs)

            surr1 = ratio * advantages
            surr2 = torch.clamp(ratio, 1.0 - self.clip_epsilon, 1.0 + self.clip_epsilon) * advantages

            actor_loss = -torch.min(surr1, surr2).mean() - self.entropy_coef * entropy

            self.optimizer_actor.zero_grad()
            actor_loss.backward()
            torch.nn.utils.clip_grad_norm_(self.actor.parameters(), 0.5)
            self.optimizer_actor.step()

            # --- 2. Criticの更新 ---
            critic_epoch_losses = []

            for i in range(self.num_agents):
                target_agent_id = torch.full((batch_size,), i, dtype=torch.long, device=self.device)

                # 🛠️ 変更点: 綺麗にセパレートされたglobal_statesが、新設したCriticのMLPベースのフォワードに入ります
                values = self.critic(global_states, target_agent_id).squeeze(-1) # (batch,)

                target_returns = returns[:, i] # (batch,)

                critic_loss = nn.SmoothL1Loss()(values, target_returns)
                critic_epoch_losses.append(critic_loss)

            # エージェント全員分のCriticロスを合計し、係数を掛け合わせて更新
            total_critic_loss = torch.stack(critic_epoch_losses).mean() * self.value_coef

            self.optimizer_critic.zero_grad()
            total_critic_loss.backward()
            torch.nn.utils.clip_grad_norm_(self.critic.parameters(), 0.5)
            self.optimizer_critic.step()

            actor_losses.append(actor_loss.item())
            critic_losses.append(total_critic_loss.item())
            entropies.append(entropy.item())

        return np.mean(actor_losses), np.mean(critic_losses), np.mean(entropies)

    def load_checkpoint(self, checkpoint_path):
        checkpoint = torch.load(checkpoint_path, map_location=self.device)
        self.actor.load_state_dict(checkpoint['actor_state_dict'])
        self.critic.load_state_dict(checkpoint['critic_state_dict'])
        self.cnn_encoder.load_state_dict(checkpoint['cnn_encoder_state_dict'])
        self.critic_encoder.load_state_dict(checkpoint['critic_encoder_state_dict'])

        self.optimizer_actor.load_state_dict(checkpoint['optimizer_actor_state_dict'])
        self.optimizer_critic.load_state_dict(checkpoint['optimizer_critic_state_dict'])

        episode = checkpoint['episode']
        print(f"チェックポイントを読み込み: {checkpoint_path} (episode: {episode})")
        return episode

import numpy as np
from collections import defaultdict

class MultiAgentBuffer:
    def __init__(self, num_agents, obs_dim, state_dim, action_dim):
        self.num_agents = num_agents
        self.obs_dim = obs_dim
        self.state_dim = state_dim
        self.action_dim = action_dim

        self.buffer = {
            'obs': [],
            'actions': [],
            'rewards': [],
            'global_states': [],
            'log_probs': [],
            'values': [],       # 各エージェントの辞書形式 {'pursuer_0': v, ...}
            'terminated': [],
            'truncated': [],
            'advantages': [],   # compute_advantages内で辞書のリストとして生成
            'returns': [],      # compute_advantages内で辞書のリストとして生成
        }

        self.episode_lengths = []
        self.current_episode_steps = 0

    def store(self, obs_dict, action_dict, reward_dict, global_state,
              log_prob_dict, value_dict, terminated, truncated):
        """
        環境の1ステップのデータを保存
        """
        self.buffer['obs'].append(obs_dict)
        self.buffer['actions'].append(action_dict)
        self.buffer['rewards'].append(reward_dict)
        self.buffer['global_states'].append(global_state)
        self.buffer['log_probs'].append(log_prob_dict)
        self.buffer['values'].append(value_dict)
        self.buffer['terminated'].append(terminated)
        self.buffer['truncated'].append(truncated)

        self.current_episode_steps += 1

        # エピソードが終了（または時間切れ）したら長さを記録
        if terminated or truncated:
            self.episode_lengths.append(self.current_episode_steps)
            self.current_episode_steps = 0

    def sample(self, batch_size):
        if len(self.buffer['obs']) == 0:
            return None

        # 実際に計算が完了しているデータ数を上限にする（安全策）
        total_stored = len(self.buffer['obs'])
        indices = np.random.choice(total_stored, size=batch_size, replace=False)

        obs_batch, actions_batch, rewards_batch = [], [], []
        log_probs_batch, advantages_batch, returns_batch = [], [], []
        global_states_batch, values_batch = [], []

        for idx in indices:
            obs_step, actions_step, rewards_step = [], [], []
            log_probs_step, advantages_step, returns_step = [], [], []
            values_step = []

            for i in range(self.num_agents):
                agent_name = f'pursuer_{i}'
                obs_step.append(self.buffer['obs'][idx][agent_name])
                actions_step.append(self.buffer['actions'][idx][agent_name])
                log_probs_step.append(self.buffer['log_probs'][idx][agent_name])
                values_step.append(self.buffer['values'][idx][agent_name])

                # MAPPO.update側が「rewards」というキーでCriticのターゲット（Returns）を要求するため、
                # ここで returns の値を rewards_step にマッピングします。
                if idx < len(self.buffer['returns']) and self.buffer['returns'][idx] is not None and agent_name in self.buffer['returns'][idx]:
                    rewards_step.append(self.buffer['returns'][idx][agent_name])
                else:
                    rewards_step.append(0.0)

                # 安全に個別advantageを取得
                if idx < len(self.buffer['advantages']) and self.buffer['advantages'][idx] is not None and agent_name in self.buffer['advantages'][idx]:
                    advantages_step.append(self.buffer['advantages'][idx][agent_name])
                else:
                    advantages_step.append(0.0)

            obs_batch.append(obs_step)
            actions_batch.append(actions_step)
            rewards_batch.append(rewards_step)
            log_probs_batch.append(log_probs_step)
            advantages_batch.append(advantages_step)
            values_batch.append(values_step)

            # global_statesの保存 (batch, state_dim)
            global_states_batch.append(self.buffer['global_states'][idx])

        batch = {
            'obs': np.array(obs_batch, dtype=np.float32),                 # (batch, num_agents, obs_dim)
            'actions': np.array(actions_batch, dtype=np.int64),           # (batch, num_agents)
            'rewards': np.array(rewards_batch, dtype=np.float32),         # (batch, num_agents) ※実質は個別Returns
            'global_states': np.array(global_states_batch, dtype=np.float32), # (batch, state_dim)
            'log_probs': np.array(log_probs_batch, dtype=np.float32),     # (batch, num_agents)
            'values': np.array(values_batch, dtype=np.float32),           # (batch, num_agents)
            'advantages': np.array(advantages_batch, dtype=np.float32),   # (batch, num_agents)
        }
        return batch

    def compute_advantages(self, gamma=0.99, gae_lambda=0.95):
        total_steps = len(self.buffer['obs'])
        advantages = [None] * total_steps
        returns = [None] * total_steps

        start_idx = 0
        for ep_len in self.episode_lengths:
            end_idx = start_idx + ep_len

            # 該当エピソードのデータをスライス
            rewards_ep = self.buffer['rewards'][start_idx:end_idx]
            values_ep = self.buffer['values'][start_idx:end_idx]
            terminated_ep = self.buffer['terminated'][start_idx:end_idx]
            truncated_ep = self.buffer['truncated'][start_idx:end_idx]

            for agent_idx in range(self.num_agents):
                agent_name = f'pursuer_{agent_idx}'
                agent_rewards = [r[agent_name] for r in rewards_ep]
                agent_values = [v[agent_name] for v in values_ep]

                advantage_ep = np.zeros(ep_len)
                return_ep = np.zeros(ep_len)

                gae = 0.0

                # 🌟 時間切れ（truncated）発生時のブートストラップ初期値設定の厳密化
                # エピソードの最後のステップの「次の状態の価値 V(s_{t+1})」を決定します
                if truncated_ep[-1]:
                    # 時間切れの場合は、途中で遮断されただけなので最後の状態の価値をブートストラップとして使う
                    next_value = agent_values[-1]
                    future_return = agent_values[-1]
                else:
                    # 通常終了（terminated）またはその他の場合は 0.0
                    next_value = 0.0
                    future_return = 0.0

                # 未来(お尻)から過去(頭)へ向かって逆順ループ
                for t in reversed(range(ep_len)):
                    # 🌟 次のステップ t+1 が存在するか、あるいはエピソード終端かでマスクを設定
                    # 通常、PPOでは「現在のステップ t が終了フラグ（terminated）を持つ場合、次の価値を0」とマスクします
                    is_not_terminal = 0.0 if terminated_ep[t] else 1.0

                    # TD誤差 𝛿_t = r_t + 𝛾 * V(s_{t+1}) * mask - V(s_t)
                    delta = agent_rewards[t] + gamma * next_value * is_not_terminal - agent_values[t]

                    # GAEの累積: 𝛿_t + 𝛾 * 𝜆 * GAE_{t+1} * mask
                    gae = delta + gamma * gae_lambda * is_not_terminal * gae
                    advantage_ep[t] = gae

                    # 割引累積報酬（Return）の計算
                    future_return = agent_rewards[t] + gamma * is_not_terminal * future_return
                    return_ep[t] = future_return

                    # 1つ過去のステップ（t-1）にとっての「未来の価値 V(s_{t+1})」は、現在の V(s_t)
                    next_value = agent_values[t]

                # 各エージェントの計算結果をステップごとの辞書に戻して全体へ格納
                for t_idx in range(ep_len):
                    global_idx = start_idx + t_idx
                    if advantages[global_idx] is None:
                        advantages[global_idx] = {}
                        returns[global_idx] = {}
                    advantages[global_idx][agent_name] = advantage_ep[t_idx]
                    returns[global_idx][agent_name] = return_ep[t_idx]

            start_idx = end_idx

        self.buffer['advantages'] = advantages
        self.buffer['returns'] = returns

    def clear(self):
        for key in self.buffer:
            self.buffer[key] = []
        self.episode_lengths = []
        self.current_episode_steps = 0

    def __len__(self):
        return len(self.buffer['obs'])

from google.colab import drive
import os
drive.mount('/content/drive')

CHECKPOINT_DIR = "/content/drive/MyDrive/rl_pursuit"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
def save_checkpoint(mappo, episode, checkpoint_dir="checkpoints"):
    """
    MAPPOのチェックポイントを保存

    Args:
        mappo: MAPPOインスタンス
        episode: 現在のエピソード番号
        checkpoint_dir: 保存ディレクトリ
    """
    os.makedirs(checkpoint_dir, exist_ok=True)
    checkpoint_path = os.path.join(checkpoint_dir, f"mappo_episode.pth")

    # 現在のデバイスを退避（CPU/GPUに柔軟に対応するため）
    actor_device = next(mappo.actor.parameters()).device
    critic_device = next(mappo.critic.parameters()).device

    # 安全な保存のために一度モデルをCPUへ退避
    mappo.actor.cpu()
    mappo.critic.cpu()

    # 状態辞書の作成
    save_dict = {
        'episode': episode,
        'actor_state_dict': mappo.actor.state_dict(),
        'critic_state_dict': mappo.critic.state_dict(),
        'cnn_encoder_state_dict': mappo.cnn_encoder.state_dict(),      # Actor側のCNN
        'critic_encoder_state_dict': mappo.critic_encoder.state_dict(),  # Critic側のCNN (追加)
        'optimizer_actor_state_dict': mappo.optimizer_actor.state_dict(),
        'optimizer_critic_state_dict': mappo.optimizer_critic.state_dict(),
    }

    torch.save(save_dict, checkpoint_path)

    # モデルを元のデバイスに復元
    mappo.actor.to(actor_device)
    mappo.critic.to(critic_device)

    print(f"Checkpoint saved: {checkpoint_path}")


def load_checkpoint(mappo, checkpoint_path, device='cpu'):
    """
    外部関数としてMAPPOのチェックポイントを読み込み

    Args:
        mappo: MAPPOインスタンス
        checkpoint_path: .pthファイルへのパス
        device: マップ先のデバイス設定
    """
    checkpoint = torch.load(checkpoint_path, map_location=device)

    # 各種ネットワークのウェイトをロード
    mappo.actor.load_state_dict(checkpoint['actor_state_dict'])
    mappo.critic.load_state_dict(checkpoint['critic_state_dict'])
    mappo.cnn_encoder.load_state_dict(checkpoint['cnn_encoder_state_dict'])
    mappo.critic_encoder.load_state_dict(checkpoint['critic_encoder_state_dict']) # 追加

    # オプティマイザの状態をロード
    mappo.optimizer_actor.load_state_dict(checkpoint['optimizer_actor_state_dict'])
    mappo.optimizer_critic.load_state_dict(checkpoint['optimizer_critic_state_dict'])

    episode = checkpoint['episode']
    print(f"チェックポイントを読み込み: {checkpoint_path} (episode: {episode})")
    return episode

import os
from collections import deque
import numpy as np
import torch

# =====================================================================
# ハイパーパラメータ & 設定
# =====================================================================
max_episodes = 1000
max_cycles = 500
batch_size = 64
update_epochs = 3
gamma = 0.99
gae_lambda = 0.95
checkpoint_interval = 10
CHECKPOINT_DIR = "/content/drive/MyDrive/rl_pursuit"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 環境とラッパの初期化 (PursuitWrapper が定義されている前提)
env = PursuitWrapper(render_mode=None, max_cycles=max_cycles)
num_agents = env.num_agents
obs_dim = env.obs_dim
state_dim = env.state_dim
action_dim = env.action_dim

# MAPPOの初期化
mappo = MAPPO(
    num_agents=num_agents,
    obs_dim=obs_dim,
    state_dim=state_dim,
    action_dim=action_dim,
    gamma=gamma,
    gae_lambda=gae_lambda,
    device=device
)

print("=== MAPPO（CNN & IDベース）学習開始 ===")
print(f"エージェント数: {num_agents}")
print(f"観測次元: {obs_dim}")
print(f"グローバル状態次元: {state_dim}")
print(f"行動空間サイズ: {action_dim}")
print(f"使用デバイス: {device}")

# チェックポイントの再開処理
path_checkpoint = os.path.join(CHECKPOINT_DIR, "mappo_episode.pth")
start_episode = 0
if os.path.exists(path_checkpoint):
    start_episode = load_checkpoint(mappo, path_checkpoint, device=device)
    print(f"再開エピソード: {start_episode}")

# モニタリング用のバッファ
reward_buffer = deque(maxlen=100)
capture_buffer = deque(maxlen=100)  # 1エピソードあたりの捕獲数

# =====================================================================
# メイン学習ループ
# =====================================================================
for episode in range(start_episode, max_episodes):
    env.reset()
    episode_reward = 0.0
    episode_captures = 0  # このエピソードの捕獲数

    # AEC環境のループ
    for agent in env.env.agent_iter():
        # 現在アクティブなエージェントの観測と終了フラグを取得
        _, _, terminated, truncated, _ = env.env.last(agent)

        if terminated or truncated:
            action = None
        else:
            # 1. 全エージェントの現在の最新観測を配列に集約
            obs_list = []
            for i in range(num_agents):
                agent_name = f'pursuer_{i}'
                if agent_name in env.env.agents:
                    agent_obs = env.get_obs(agent_name)
                    obs_list.append(agent_obs if agent_obs is not None else np.zeros(obs_dim, dtype=np.float32))
                else:
                    obs_list.append(np.zeros(obs_dim, dtype=np.float32))

            # 2. テンソル化してポリシー(Actor)に入力
            obs_tensor = torch.FloatTensor(np.array(obs_list)).to(device)  # (num_agents, obs_dim)

            # MAPPOで全エージェント分の行動と確率を同時に推論
            actions_np, log_probs_np = mappo.get_action(obs_tensor)

            # 現在のループ対象エージェントの行動をインデックスから抽出
            agent_idx = int(agent.split('_')[-1])
            action = actions_np[agent_idx]

        # 3. 環境を1ステップ進める
        reward, terminated, truncated, info = env.step(agent, action)
        episode_reward += reward

        # Pursuit環境特有の捕獲報酬(+5)をカウント
        if reward == 5.0:
            episode_captures += 1

        # 4. バッファに保存するためのステップ全体の辞書データを構築
        obs_dict = {}
        action_dict = {}
        reward_dict = {}
        log_prob_dict = {}
        value_dict = {}

        # 全エージェントの情報を辞書にマッピング
        for i in range(num_agents):
            agent_name = f'pursuer_{i}'
            if agent_name in env.env.agents:
                agent_obs = env.get_obs(agent_name)
                obs_dict[agent_name] = agent_obs if agent_obs is not None else np.zeros(obs_dim, dtype=np.float32)

                # 現在の行動決定エージェント以外は0（プレースホルダー）として扱う
                if agent_name == agent:
                    action_dict[agent_name] = action if action is not None else 0
                    reward_dict[agent_name] = reward
                else:
                    action_dict[agent_name] = 0
                    reward_dict[agent_name] = 0.0

                log_prob_dict[agent_name] = log_probs_np[i] if 'log_probs_np' in locals() else 0.0
            else:
                obs_dict[agent_name] = np.zeros(obs_dim, dtype=np.float32)
                action_dict[agent_name] = 0
                reward_dict[agent_name] = 0.0
                log_prob_dict[agent_name] = 0.0

        # 5. Centralized Criticによる価値推定（全エージェント個別の視点から算出）
        global_state_list = [obs_dict[f'pursuer_{k}'] for k in range(num_agents)]
        global_state_tensor = torch.FloatTensor(np.array(global_state_list)).unsqueeze(0).to(device) # (1, num_agents, obs_dim)

        for i in range(num_agents):
            agent_name = f'pursuer_{i}'
            if agent_name in env.env.agents:
                target_id_tensor = torch.tensor([i], dtype=torch.long, device=device)
                with torch.no_grad():
                    # 各エージェント固有ID付きのCentralized CriticからV(s)を取得
                    val = mappo.critic(global_state_tensor, target_id_tensor).item()
                value_dict[agent_name] = val
            else:
                value_dict[agent_name] = 0.0

        # 6. 1次元化した global_state と共に、マルチエージェントバッファへ格納
        global_state_flat = np.array(global_state_list).flatten() # (num_agents * obs_dim,)
        mappo.buffer.store(
            obs_dict, action_dict, reward_dict, global_state_flat,
            log_prob_dict, value_dict, terminated, truncated
        )

        if terminated or truncated:
            break

    # =====================================================================
    # エピソード終了後のネットワーク更新処理
    # =====================================================================
    reward_buffer.append(episode_reward)
    capture_buffer.append(episode_captures)

    avg_reward = np.mean(reward_buffer)
    avg_captures = np.mean(capture_buffer)

    print(f"Episode {episode}: Reward = {episode_reward:.2f}, "
          f"Captures = {episode_captures}, "
          f"Avg Reward = {avg_reward:.2f}, "
          f"Avg Captures = {avg_captures:.2f}")

    # アドバンテージ（GAE）とリターンの計算
    mappo.buffer.compute_advantages(gamma=gamma, gae_lambda=gae_lambda)

    # ミニバッチサンプリングを用いてPPOの更新（ネットワーク最適化）
    actor_losses, critic_losses, entropies = [], [], []

    for _ in range(update_epochs):
        batch = mappo.buffer.sample(batch_size)
        if batch is not None:
            # mappo.updateの内部でエポックを回すため、1回呼び出す
            actor_loss, critic_loss, entropy = mappo.update(batch, epochs=1)

            actor_losses.append(actor_loss)
            critic_losses.append(critic_loss)
            entropies.append(entropy)

    if len(actor_losses) > 0:
        print(f"Actor Loss: {np.mean(actor_losses):.4f} | "
              f"Critic Loss: {np.mean(critic_losses):.4f} | "
              f"Avg Entropy: {np.mean(entropies):.4f}")

    # 次のエピソードに備えてバッファをリセット
    mappo.buffer.clear()

    # 一定間隔でチェックポイントをセーブ
    if episode % checkpoint_interval == 0 and episode > 0:
        save_checkpoint(mappo, episode, checkpoint_dir=CHECKPOINT_DIR)

env.close()
print("=== MAPPO（CNN & IDベース）学習完了 ===")

import os
import numpy as np
import torch
import imageio
from PIL import Image

# =====================================================================
# 設定（学習コードと共通）
# =====================================================================
max_cycles = 500
CHECKPOINT_DIR = "/content/drive/MyDrive/rl_pursuit"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# PursuitWrapper の初期化（render_mode="human" で可視化）
env_wrapper = PursuitWrapper(render_mode="human", max_cycles=max_cycles)
num_agents = env_wrapper.num_agents
obs_dim = env_wrapper.obs_dim
state_dim = env_wrapper.state_dim
action_dim = env_wrapper.action_dim

# MAPPO の初期化（学習時と同じ構成）
mappo = MAPPO(
    num_agents=num_agents,
    obs_dim=obs_dim,
    state_dim=state_dim,
    action_dim=action_dim,
    gamma=0.99,
    gae_lambda=0.95,
    device=device
)

# チェックポイントの読み込み
path_checkpoint = os.path.join(CHECKPOINT_DIR, "mappo_episode.pth")
if os.path.exists(path_checkpoint):
    load_checkpoint(mappo, path_checkpoint, device=device)
    print("チェックポイントを読み込みました。")
else:
    print("エラー: チェックポイントが見つかりません。")
    exit(1)

# ネットワークを評価モードに
mappo.actor.eval()
mappo.critic.eval()

print("=== MAPPO 推論モード（gif保存付き）開始 ===")
print(f"エージェント数: {num_agents}")
print(f"使用デバイス: {device}")

# =====================================================================
# フレーム保存用の設定
# =====================================================================
video_folder = "videos"
os.makedirs(video_folder, exist_ok=True)
frames = []  # 各ステップの画像を保存するリスト

# =====================================================================
# 推論ループ（1エピソード分）
# =====================================================================
env_wrapper.reset()
episode_reward = 0.0
episode_captures = 0

# AEC環境のループ（PursuitWrapper の env を使う）
for agent in env_wrapper.env.agent_iter():
    # 現在アクティブなエージェントの終了フラグを取得
    _, _, terminated, truncated, _ = env_wrapper.env.last(agent)

    if terminated or truncated:
        action = None
    else:
        # 1. 全エージェントの最新観測を集約
        obs_list = []
        for i in range(num_agents):
            agent_name = f'pursuer_{i}'
            agent_obs = env_wrapper.get_obs(agent_name)
            obs_list.append(agent_obs if agent_obs is not None else np.zeros(obs_dim, dtype=np.float32))

        # 2. テンソル化して Actor に入力（推論モード）
        obs_tensor = torch.FloatTensor(np.array(obs_list)).to(device)

        with torch.no_grad():
            actions_np, _ = mappo.get_action(obs_tensor)

        # 現在のエージェントに対応する行動を取得
        agent_idx = int(agent.split('_')[-1])
        action = actions_np[agent_idx]

    # 3. 環境を1ステップ進める（PursuitWrapper.step を使う）
    reward, terminated, truncated, info = env_wrapper.step(agent, action)
    episode_reward += reward

    # 捕獲報酬をカウント
    if reward == 5.0:
        episode_captures += 1

    # 4. 現在の画面を画像としてキャプチャして保存
    #    ※ render_mode="human" の場合、env_wrapper.env.render() で画面が更新される
    #    ここでは env_wrapper.env の render 結果を取得する方法が環境依存のため、
    #    必要に応じて env_wrapper.env.render() を呼び出し、その戻り値や画面バッファから画像を取得してください。
    #    例: frame = env_wrapper.env.render()  # 戻り値が numpy array の場合
    #        frames.append(frame)
    #
    # もし render() が None を返す場合は、別途 pygame や matplotlib で描画した画面を
    # PIL.Image や numpy array に変換して frames に追加してください。
    #
    # 以下は仮のコード例です（実際の環境に合わせて修正してください）：
    #
    frame = env_wrapper.render()  # <-- env_wrapper.env.render() から修正
    if frame is not None:
        frames.append(frame)

    if terminated or truncated:
        break

print(f"推論結果: Reward = {episode_reward:.2f}, Captures = {episode_captures}")

env_wrapper.env.close()
print("=== MAPPO 推論モード（フレーム収集）終了 ===")

# =====================================================================
# 収集したフレームを gif に保存
# =====================================================================
if len(frames) > 0:
    gif_path = os.path.join(video_folder, "pursuit_mappo.gif")
    print(f"gif 保存中: {gif_path}")

    # フレームを gif に書き出し（fps はお好みで調整）
    with imageio.get_writer(gif_path, fps=10) as writer:
        for frame in frames:
            writer.append_data(frame)

    print(f"gif 保存完了: {gif_path}")
else:
    print("フレームが収集されていません。render() の実装を確認してください。")

print("=== gif 保存処理完了 ===")

frame = env_wrapper.env.render()

