import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
from IPython.display import HTML
import io
from PIL import Image

def decoder(z):
    """
    Simple decoder: generates a colored circle image from latent variable z=(z1, z2)
    - z1: circle center x (-1~1 → 0~img_width)
    - z2: circle center y (-1~1 → 0~img_height)
    - color: computed from z1, z2 (R,G,B)
    """
    img_size = 64
    img = np.zeros((img_size, img_size, 3))  # RGB image

    # map z to image coordinates
    cx = int((z[0] + 1) / 2 * img_size)
    cy = int((z[1] + 1) / 2 * img_size)
    radius = 10

    # color from z (simple mapping)
    r = (z[0] + 1) / 2  # 0~1
    g = (z[1] + 1) / 2
    b = 1.0 - (r + g) / 2
    color = np.clip([r, g, b], 0, 1)

    # draw circle (pixel-level for simplicity)
    for y in range(img_size):
        for x in range(img_size):
            if (x - cx)**2 + (y - cy)**2 <= radius**2:
                img[y, x] = color

    return img

def plot_latent_space_grid(n_samples=10):
    """
    Scan the latent space in a grid and show the corresponding images.
    """
    z1_range = np.linspace(-1, 1, n_samples)
    z2_range = np.linspace(-1, 1, n_samples)

    fig, axes = plt.subplots(n_samples, n_samples, figsize=(12, 12))
    for i, z2 in enumerate(z2_range):
        for j, z1 in enumerate(z1_range):
            z = np.array([z1, z2])
            img = decoder(z)

            ax = axes[i, j]
            ax.imshow(img)
            ax.set_xticks([])
            ax.set_yticks([])
            if i == n_samples-1:
                ax.set_xlabel(f"z1={z1:.1f}", fontsize=8)
            if j == 0:
                ax.set_ylabel(f"z2={z2:.1f}", fontsize=8)

    plt.suptitle("Image variation as we move through the latent space z=(z1, z2)", fontsize=16)
    plt.tight_layout()
    plt.show()

def animate_latent_walk(save_gif=False, filename="latent_walk.gif"):
    """
    Animate a point z moving in the latent space and show the corresponding decoded images.
    If save_gif=True, save the animation as a GIF file.
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))

    # latent space plot
    ax1.set_xlim(-1.2, 1.2)
    ax1.set_ylim(-1.2, 1.2)
    ax1.set_xlabel("z1")
    ax1.set_ylabel("z2")
    ax1.set_title("Trajectory of z in latent space")
    ax1.grid(True)

    # image display
    ax2.set_title("Image generated by decoder")
    ax2.set_xticks([])
    ax2.set_yticks([])

    n_frames = 100
    theta = np.linspace(0, 2*np.pi, n_frames)

    def update(frame):
        ax1.clear()
        ax2.clear()

        # circular motion in latent space
        t = theta[frame]
        z1 = np.cos(t)
        z2 = np.sin(t)
        z = np.array([z1, z2])

        # latent space plot
        ax1.set_xlim(-1.2, 1.2)
        ax1.set_ylim(-1.2, 1.2)
        ax1.set_xlabel("z1")
        ax1.set_ylabel("z2")
        ax1.set_title("Trajectory of z in latent space")
        ax1.grid(True)

        # show past trajectory (faint)
        for i in range(frame):
            t_prev = theta[i]
            z1_prev = np.cos(t_prev)
            z2_prev = np.sin(t_prev)
            ax1.plot(z1_prev, z2_prev, 'o', markersize=3, color='blue', alpha=0.3)

        # current point (highlighted)
        ax1.plot(z1, z2, 'ro', markersize=8)
        ax1.text(z1+0.1, z2+0.1, f"z=({z1:.2f},{z2:.2f})", fontsize=10)

        # decode image
        img = decoder(z)
        ax2.imshow(img)
        ax2.set_title("Image generated by decoder")
        ax2.set_xticks([])
        ax2.set_yticks([])

    anim = FuncAnimation(fig, update, frames=n_frames, interval=200, repeat=True)

    if save_gif:
        # Save as GIF using PillowWriter
        writer = PillowWriter(fps=5)
        anim.save(filename, writer=writer)
        print(f"✅ GIF saved as {filename}")
        plt.close(fig)
        return None
    else:
        # Show animation in Colab
        plt.close(fig)
        return HTML(anim.to_jshtml())


if __name__ == "__main__":
    # 1. Latent space grid visualization
    print("Latent space grid visualization")
    plot_latent_space_grid(n_samples=8)

    # 2. Animated latent walk (show in Colab)
    print("Animated latent walk (display in notebook)")
    anim_html = animate_latent_walk(save_gif=False)
    if anim_html:
        display(anim_html)

    # 3. Save animation as GIF
    print("Saving animation as GIF...")
    animate_latent_walk(save_gif=True, filename="latent_walk.gif")